### ISSUE TITLE
Cannot get UUID of Users 

### ISSUE THREAD

**Issue by mirrormirage0** [OpenSTFoundation/ost-sdk-ruby#7]
user_list_object1 = ostUsersObject.list() # returns an object that includes the list of users
users_list1 = user_list_object1.data["economy_users"] # sets users_list to the array of users from the returned object
people1 = users_list1.select { |u| user_names1.include? u["name"] }.map { |r| {name: r["name"], uuid: r["uuid"] }} # filters for Alice and Bob

If you try this for "User 2", "Alice" or "Bob" , it will work fine.

If you try this for "User 1", "User 0" or any other user, you will get an empty string. not the UUID

**Comment by jasonklein** [comment]
@mirrormirage0: you are correct-ish, but there are a few things at work.

The example code in the [Quick Start Guide](https://dev.ost.com/docs/sdk_ruby.html#alice-likes-bob) is only meant to show how Ruby functions can be employed to filter the data returned to obtain specific UUIDs. The response object from `ostUsersObject.list()` is the end of the road for OST functionality.

Additionally, the suggested steps only manipulate the data returned, but do not call the API in search of specific users' UUIDs (such endpoint does not exist at present). If "User 1" or "User 0" are not among the names of returned users, the steps after calling `ostUsersObject.list()` will not precipitate them; further, if there are no elements in the returned users that match the elements of your `user_names1` array, then the end result will be an empty array (in no case should you retrieve only an empty string following the steps above or as provided in the Quick Start Guide).

Finally, in order to be flexible, the gem is not opinionated about params given to it for any given API call. For some calls, there are additional parameters available that are not utilized in the Quick Start Guide. For instance, `ostUsersObject.list()` only retrieves the first 25 users. If there are more than 25 users in your branded token economy and you would like to retrieve those other users, you can additionally pass a page number parameter, e.g., `ostUsersObject.list(page_no: 2)`, to retrieve users beyond the first 25. For more information, please see [OST KIT⍺ API | List Users - Input Parameters]( https://dev.ost.com/docs/api_users_list.html#input-parameters).

**Comment by mirrormirage0** [comment]
Thanks a ton. ostUsersObject.list(page_no: 2) does make sense. 
This could be the reason why it didn't return the user details. There were 27 users at the point of calling, and the User 2 must have fallen into Page 2.
I will have a closer look at the API, once its back for testing.
Thank you for providing the opportunity to test!

**Comment by jasonklein** [comment]
Happy to help!

Closing this issue.
